# brave-browser-beta
# Autogenerated from man page /usr/share/man/man1/brave-browser-beta.1.gz
complete -c brave-browser-beta -l user-data-dir -d 'Specifies the directory that user data (your "profile") is kept in'
complete -c brave-browser-beta -l app -d 'Runs  URL in "app mode": with no browser toolbars'
complete -c brave-browser-beta -l incognito -d 'Open in incognito mode'
complete -c brave-browser-beta -l new-window -d 'If PATH or URL is given, open it in a new window'
complete -c brave-browser-beta -l proxy-server -d 'Specify the HTTP/SOCKS4/SOCKS5 proxy server to use for requests'
complete -c brave-browser-beta -l no-proxy-server -d 'Disables the proxy server'
complete -c brave-browser-beta -l proxy-auto-detect -d 'Autodetect proxy configuration'
complete -c brave-browser-beta -l proxy-pac-url -d 'Specify proxy autoconfiguration URL'
complete -c brave-browser-beta -l password-store -d 'Set the password store to use'
complete -c brave-browser-beta -l version -d 'Show version information'
complete -c brave-browser-beta -l display -d 'See the GTK documentation for more: <http://library. gnome'

