# catfish
# Autogenerated from man page /usr/share/man/man1/catfish.1.gz
complete -c catfish -l version -d 'Show the version number and exit'
complete -c catfish -s h -l help -d 'Show the help message and exit'
complete -c catfish -s v -l verbose -d 'Show debug messages (-vv will also debug catfish_lib)'
complete -c catfish -l large-icons -d 'Use large icons'
complete -c catfish -l thumbnails -d 'Use thumbnails'
complete -c catfish -l iso-time -d 'Display time in ISO format'
complete -c catfish -l path -d 'Set the default search path'
complete -c catfish -l exact -d 'Perform exact match'
complete -c catfish -l hidden -d 'Include hidden files'
complete -c catfish -l fulltext -d 'Perform fulltext search'
complete -c catfish -l start -d 'If path and query are provided, start searching when the application is displ…'
complete -c catfish -l sort -d 'Set a default column to sort by (name|size|path|date|type),(asc|desc)'

