# dbiprof.1p
# Autogenerated from man page /usr/share/man/man1/dbiprof.1p.gz
complete -c 'dbiprof.1p' -l number -d 'Produce this many items in the report.   Defaults to 10'
complete -c 'dbiprof.1p' -l sort -d 'Sort results by the given field'
complete -c 'dbiprof.1p' -l reverse -d 'Reverses the selected sort'
complete -c 'dbiprof.1p' -l match -d 'Consider only items where the specified key matches the given value'
complete -c 'dbiprof.1p' -l exclude -d 'Remove items for where the specified key matches the given value'
complete -c 'dbiprof.1p' -l case-sensitive -d 'Using this option causes --match and --exclude to work case-sensitively'
complete -c 'dbiprof.1p' -l delete -d 'Sets the \\f(CW\\*(C`DeleteFiles\\*(C\' option to DBI::ProfileData which causes t…'
complete -c 'dbiprof.1p' -l dumpnodes -d 'Print the list of nodes in the form of a perl data structure'

