# hddtemp
# Autogenerated from man page /usr/share/man/man8/hddtemp.8.gz
complete -c hddtemp -s b -l drivebase -d 'Display the database file that allows hddtemp to recognize a supported drive'
complete -c hddtemp -s D -l debug -d 'Display various S. M. A. R. T.  fields and their values'
complete -c hddtemp -s d -l daemon -d 'Execute hddtemp in TCP/IP daemon mode (port 7634 by default)'
complete -c hddtemp -s f -l file -d 'Specify the database file to use'
complete -c hddtemp -s F -l foreground -d 'Don\'t fork into the background even in daemon mode'
complete -c hddtemp -s l -l listen -d 'Listen on a specific address'
complete -c hddtemp -s n -l numeric -d 'Print only the temperature (without the unit)'
complete -c hddtemp -s p -l port -d 'Port number to listen to (in TCP/IP daemon mode)'
complete -c hddtemp -s s -l separator -d 'Separator to use between fields (in TCP/IP daemon mode)'
complete -c hddtemp -s S -l syslog -d 'Switch to daemon mode and log temperatures to syslog every s seconds'
complete -c hddtemp -s q -l quiet -d 'Don\'t check if the drive is supported'
complete -c hddtemp -s u -l unit -d 'Force output temperature either in Celsius or Fahrenheit'
complete -c hddtemp -s v -l version -d 'Display hddtemp version number'
complete -c hddtemp -s w -l wake-up -d 'Wake-up the drive if needed (ATA drives only)'
complete -c hddtemp -s 4 -d 'Listen on IPv4 sockets only'

