# light
# Autogenerated from man page /usr/share/man/man1/light.1.gz
complete -c light -s H -d 'Show help text and exit'
complete -c light -s V -d 'Show program version and exit'
complete -c light -s L -d 'List available devices'
complete -c light -s A -d 'Increase brightness by value'
complete -c light -s U -d 'Decrease brightness by value'
complete -c light -s S -d 'Set brightness to value'
complete -c light -s G -d 'Get brightness, default'
complete -c light -s N -d 'Set minimum brightness to value'
complete -c light -s P -d 'Get minimum brightness'
complete -c light -s O -d 'Save current brightness'
complete -c light -s I -d 'Restore previously saved brightness El OPTIONS The behavior of the above comm…'
complete -c light -s r -d 'Interpret input and output values in raw mode'
complete -c light -s s -d 'Specify device target path.   Use L to list available devices'
complete -c light -s v -d 'Set verbosity level, by default light only outputs read values: Pp -tag -widt…'

