# simplescreenrecorder
# Autogenerated from man page /usr/share/man/man1/simplescreenrecorder.1.gz
complete -c simplescreenrecorder -l help -d 'Show this help message'
complete -c simplescreenrecorder -l version -d 'Show version information'
complete -c simplescreenrecorder -l settingsfile -d 'Load and save program settings to \\,FILE\\/.  If omitted, \\,~/. ssr/settings'
complete -c simplescreenrecorder -l logfile -d 'Write log messages to \\,FILE\\/.  If \\,FILE\\/ is omitted, \\,~/'
complete -c simplescreenrecorder -l statsfile -d 'Write recording statistics to \\,FILE\\/'
complete -c simplescreenrecorder -l no-systray -d 'Don\'t show the system tray icon'
complete -c simplescreenrecorder -l start-hidden -d 'Start the application in hidden form'
complete -c simplescreenrecorder -l start-recording -d 'Start the recording immediately'
complete -c simplescreenrecorder -l activate-schedule -d 'Activate the recording schedule immediately'
complete -c simplescreenrecorder -l syncdiagram -d 'Show synchronization diagram (for debugging)'
complete -c simplescreenrecorder -l benchmark -d 'Run the internal benchmark.  COMMANDS ACCEPTED THROUGH STDIN'

