# ssr-glinject
# Autogenerated from man page /usr/share/man/man1/ssr-glinject.1.gz
complete -c ssr-glinject -l help -d 'Show help message'
complete -c ssr-glinject -l glx-debug -d 'Enables GLX debugging'
complete -c ssr-glinject -l relax-permissions -d 'Uses mode 666 instead of 600 for shared memory, so that other users can recor…'
complete -c ssr-glinject -l channel -d 'Channel name to use.  The default is \'channel-USERNAME\''

