# winedbg
# Autogenerated from man page /usr/share/man/man1/winedbg.1.gz
complete -c winedbg -l commandstring -d 'winedbg will execute the command string as if it was keyed on winedbg command…'
complete -c winedbg -l filefilename -d 'winedbg will execute the list of commands contained in file filename as if th…'
complete -c winedbg -l no-start -d 'Don\'t launch gdb directly; instead, print the target remote GDB command to ex…'
complete -c winedbg -l portport -d 'Start the GDB proxy debugging server on the given port'
complete -c winedbg -l with-xterm -d 'This will run the gdb front end in a new  xterm (1) window instead of using t…'
complete -c winedbg -l gdb -d 'winedbg will be used as a proxy for gdb'
complete -c winedbg -l auto -d 'This mode is used when winedbg is set up in AeDebug registry entry as the def…'
complete -c winedbg -l minidump -d 'This mode is similar to the --auto one, except that instead of printing the i…'
complete -c winedbg -l command -d 'winedbg will execute the command string as if it was keyed on winedbg command…'
complete -c winedbg -l file -d 'winedbg will execute the list of commands contained in file filename as if th…'
complete -c winedbg -l port -d 'Start the GDB proxy debugging server on the given port'

